Get by name func
cse112-group10/cse112-sp22-group10 pull request #59
Opened 2022-05-31 21:16 UTC by demyinn00

# Resolves #52 
After creating your PR, please complete this template!

### What were your changes
- Created a new route and model for the route:
     - getByTitle in /source/backend/database/models/recipes.js
     - GET /recipes/searchByTitle/:title in /source/backend/routes/recipes.js
- I modified the getByName function inside /source/frontend/assets/scripts/database.js
I have commented out the countRecipes function because I'm sure it's unnecessary and I will completely remove it after it's been approved. 

### What specifically should be checked
- Test if this works. I had trouble testing so I'm not sure if the site works with that search. I am confident the route works because I was able to test that on postman.

2022-05-31 22:14 UTC, mingkaili requested changes

2022-05-31 22:14 UTC, mingkaili commented on source/frontend/assets/scripts/database.js
> +// async function countRecipes(recipeNames) {
We can safely delete lines 136 - 154

2022-06-02 16:59 UTC, demyinn00 commented on source/backend/database/models/recipesModel.js
> +    .where({ title });
Should the `title` be title case or should it be lowercase? Inside the database everything seems to be title case, or does `whereRaw` ignore that? I looked into `whereRaw` and `whereLike` and it seems it is case sensitive, so I am assuming it needs to be title case?

2022-06-02 16:59 UTC, demyinn00 commented on source/frontend/assets/scripts/database.js
> +        const recipesArray = await fetch(`${url}/recipes/searchByTitle/${recipeName}`);
Yes that makes perfect sense. I completely forgot that async basically does everything a promise can, but it's more readable. Thank you

2022-06-06 02:55 UTC, demyinn00 commented on source/frontend/assets/scripts/database.js
> +        const recipesArray = await fetch(`${url}/recipes/searchByTitle/${recipeName}`);
Fixed!

2022-06-06 06:03 UTC, merged